apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-lyhkdmaa
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-lyhkdmaa:36f90ce93306eca6739f69c8ab718bdc99bbb550@sha256:ee631a23a4f6937a8d73b8bece03d7433d9ff6f7af2e640a3080dd057278c027
          name: container-image
